name: Snyk CI
on: 
 push:
  branches: DevOps
jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build a Docker image
      run: docker build -t softdsim/front ./frontend
    - name: Run Snyk to check Docker image for vulnerabilities
      id: vulneberalities-frontend
      continue-on-error: true
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: softdsim/front
        args: --file=./frontend/Dockerfile
    - name: Upload result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: snyk.sarif
