name: Snyk CI
on: 
 push:
  branches: DevOps
jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build a Docker image
      run: docker build -t softdsim/backend ./Backend
    - name: Run Snyk to check Docker image for vulnerabilities
      id: vulneberalities-backend
      continue-on-error: true
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: softdsim/backend
        args: --file=./Backend/Dockerfile
              --sarif-file-output=./Backend/BackendSnyk.sarif
        sarif: false
        json: true
    - name: Upload result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: ./Backend
